/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {


    @Test
    void checkBaseCase() {
        // Give Input 
        String simulatedInput = "2\n"; // user types "Alice" then Enter
        System.setIn(new ByteArrayInputStream(simulatedInput.getBytes()));

        // Call method that reads from Scanner(System.in)
        String result = Main.readName(); // e.g., method that does `new Scanner(System.in).nextLine()`
        assertEquals("Alice", result);

        System.setIn(System.in); // Reset System.in

    }

}
