/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;   // <- needed for System.setIn
import java.io.ByteArrayOutputStream; // <- needed to capture output
import java.io.PrintStream;           // <- needed for System.setOut


class MainTest {

    @Test
    void checkBaseCase() {
        // Give Input 
        String simulatedInput = String.join("\n",
                "1",
                "3",
                " o ",
                "ooo",
                " o "
        ) + "\n"; 
        System.setIn(new ByteArrayInputStream(simulatedInput.getBytes()));

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(outputStream));

        // Run the program
        Main.main(new String[]{});

        // Reset System.out
        System.setOut(originalOut);

        String expectedOutput = "4";

        System.out.println(outputStream.toString());

        assertEquals(expectedOutput, outputStream.toString());

    }

}
